language: cpp

sudo: false
dist: trusty

notifications:
    email: false

compiler:
    - gcc

addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - g++-5
        - libgsl0-dev
        - libgsl0ldbl

before_script:
    - export CXX=g++-5
    - export CC=gcc-5
    - ./install_libseq.sh

script:
# The LD_LIBRARY_PATH seems to be needed to get the clang linker to find libsequence b/c it is installed in $HOME
    - export LD_LIBRARY_PATH=$HOME/lib
    - ./configure --prefix=$HOME CXXFLAGS="-O2 -I$HOME/include" LDFLAGS="$LDFLAGS -L$HOME/lib" && make && make check && make install
    - $HOME/bin/fwdppConfig --version
