language: cpp

compiler:
 - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -f install zlib1g zlib1g-dev libboost-test-1.55.0 libboost-test-1.55-dev libboost-system1.55.0 libboost-system1.55-dev libgsl0-dev libgsl0ldbl
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi


install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

  # clang 3.5
  #- if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq clang-3.5; fi
  #- if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.5"; fi
