language: cpp

sudo: false

notifications:
  email: false

language: cpp

compiler:
  - gcc
  - clang-3.5

install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
# - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.5" CC="clang-3.5"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang
    - zlib1g
    - zlib1g-dev
    - libboost-dev
    - libboost-system-dev
    - libboost-test-dev
    - libgsl0-dev
    - libgsl0ldbl

before_script:
 ./install_libseq.sh

script:
 - ./configure --prefix=$HOME CXXFLAGS="-O2 -I$HOME/include" LDFLAGS="$LDFLAGS -L$HOME/lib" && make && make check
 - $HOME/bin/fwdppConfig --version