language: cpp

sudo: false

language: cpp

compiler:
  - gcc
  - clang

install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - zlib1g
    - zlib1g-dev
    - libboost-dev
    - libboost-system-dev
    - libboost-test-dev
    - libgsl0-dev
    - libgsl0ldbl

before_script:
 ./install_libseq.sh

script:
 ./configure CXXFLAGS=-"-O2 -I$HOMEinclude" LDFLAGS="$LDFLAGS -L$HOME/lib" && make && make check